/*

 BACKGROUNDMAP_EXAMPLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\users\daniel\Desktop\School\cse310\sprint3_cse310\01helloworld\sprites\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 40
#define backgroundmapHeight 18
#define backgroundmapBank 0

extern unsigned char backgroundmap[];

/* End of BACKGROUNDMAP_EXAMPLE.H */
