/*

 NUTTY_ANIMATED.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/



/* Start of tile array. */
/*NOTE:There are 4 rows bc 2 of these rows are for each animated tile*/
unsigned char Nutmeg[] =
{
  0x00,0x00,0x80,0x80,0x05,0x45,0x47,0x47,
  0x3F,0x3F,0x2A,0x3E,0x5C,0x7C,0x42,0x42,
  0x05,0x05,0x07,0x07,0x07,0x07,0x2E,0x6E,
  0x99,0x9D,0x3C,0x2C,0x44,0x44,0x00,0x00
};

/* End of NUTTY_ANIMATED.C */
