/*

 SIMPLEBACKGROUNDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\daniel\School\cse310\sprint3_cse310\gameboygame_daniel\sprites\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define simplebackgroundmapWidth 40
#define simplebackgroundmapHeight 18
#define simplebackgroundmapBank 0

unsigned char windowmap[] =
{
  0x12,0x0F,0x16,0x16,0x19
};

/* End of SIMPLEBACKGROUNDMAP.C */
